### ISSUE TITLE
predictions

### ISSUE THREAD

**Issue by luantunez** [catarina-barata/skin-hierarchy#1]
Hello and thank you for sharing your work!
Would it be possible to perform predictions with your pretrained model?
Where is the script for that?
Thank you in advance, Lucia

**Comment by catarina-barata** [comment]
Dear Lucia,

Thank you for your interest in our work.

The weights of our trained models are not available, since we used 5-fold cross validation and this would force us to release several models. 

Nonetheless, the 5 folds used for training/validation are available and you can reproduce our experimental conditions and train your own model(s).
To perform predictions, you can adapt the code that we use for the validation stage, namely the **apply_lstm_gem** function, that is implemented in the **hierarchical_attention_train.py** script.
